FROM analytics-docker.artifactory.zgtools.net/artificial-intelligence/ai-platform/aip-py36-cpu:2.3.0e77164a.hs-aip-2838
COPY . /home/zservice/metaflow
RUN pip install --upgrade --no-deps --force-reinstall -e /home/zservice/metaflow
