FROM analytics-docker.artifactory.zgtools.net/artificial-intelligence/ai-platform/aip-py39-cpu-cicd:4.0.1380
ARG KFP_STEP_IMAGE_ARG
ENV KFP_STEP_IMAGE=$KFP_STEP_IMAGE_ARG
COPY . /home/zservice/metaflow
RUN pip install --upgrade --force-reinstall -e /home/zservice/metaflow
RUN pip install \
    pytest==6.1.2 \
    pytest-xdist==2.1.0 \
    pytest-cov==2.10.1 \
    subprocess-tee==0.3.2 \
    pyyaml==5.4.1 \
    kubernetes==18.20.0
