channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=3.0.16
- jupyter-offlinenotebook=0.2
- nbconvert=6
# Python Kernel
- ipykernel=5.1
- xeus-python=0.12.4
- ipywidgets=7.6.3
- ipytree=0.2.1
- widgetsnbextension=3.5.1
- ipyleaflet=0.14.0
#- altair=4.1
- geopy=2.1.0
#- bqplot=0.12.20
# - metaflow
- matplotlib=3.3.4
- pandas=1.2.4
- Pillow=8.2.0
- python=3.7
- pydot=1.4.2
- qgrid=1.3.1
- scikit-learn=0.24.2
- seaborn=0.11
- sidecar=0.5.1
- statsmodels=0.12.2
- sympy=1.4
- pyyaml
#- traittypes==0.2.1
- invoke=1.2
